# Generated by Django 4.2.3 on 2023-08-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Discount', 'primary'), ('Sale', 'secondary'), ('New', 'danger')], max_length=9),
        ),
    ]
