# Generated by Django 4.2.3 on 2023-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is test description'),
            preserve_default=False,
        ),
    ]
